### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by vshokorov** [vshokorov/Domen-Adaptation#1]
Мини блог о курсовой работе.

**Comment by vshokorov** [comment]
Разобрать статьи:
- [ ] [Байесовский выбор моделей. Дистилляция на основе априорной информации.](https://www.youtube.com/watch?v=R3XOEMiVfq0&list=WL&index=3)
- [ ] [Lecture 10: GAN evaluation. SAGAN, BigGAN, ProGAN, StyleGAN. [DGM course, 2020], Roman Isachenko](https://www.youtube.com/watch?v=kKmQlLOQLIY&list=PLk4h7dmY2eYHjH6wjO1Wytb2ipXJX-aWj&index=10)
- [x] [ALAE](https://github.com/podgorskiy/ALAE)
> ![image](https://user-images.githubusercontent.com/48180167/100659868-4d340b00-3362-11eb-94d6-4d6e029ed895.png)
- [x] [Unsupervised Discovery of Interpretable Directions in the GAN Latent Space](https://arxiv.org/pdf/2002.03754.pdf)
> ![image](https://user-images.githubusercontent.com/48180167/100673977-7742f880-3375-11eb-9282-18e95abe07fe.png)
> В статье была отсылка на [Disentangling GAN with One-Hot Sampling and Orthogonal Regularization](https://arxiv.org/pdf/1905.10836.pdf)
> > Тут используют классификаторы, предварительно обученные на наборе данных CelebA, чтобы предсказать определенные атрибуты лица. Эти классификаторы затем используются для получения псевдомаркировок для генерируемых изображений и их скрытых кодов. На основе этих псевдо-меток в латентном пространстве строится разделяющая гиперплоскость, и нормаль к этой гиперплоскости становится направлением, которое захватывает соответствующий атрибут
> [A Spectral Regularizer for Unsupervised Disentanglement](https://arxiv.org/pdf/1812.01161.pdf)
> > В работе строиться распутываение латентного пространства обученного GAN. Строятся интерпретируемая кривая по собственным векторам матрицы якоби GAN, как по градиентам. 
- [ ] [MULTI-STEP DECENTRALIZED DOMAIN ADAPTATION](https://openreview.net/attachment?id=Hkg0olStDr&name=original_pdf)
- [ ] [FEDERATED ADVERSARIAL DOMAIN ADAPTATION](https://openreview.net/attachment?id=HJezF3VYPB&name=original_pdf)
- [ ] [Navigating the GAN Parameter Space for Semantic Image Editing](https://arxiv.org/pdf/2011.13786.pdf)

**Comment by vshokorov** [comment]
[Efficient Learning of Domain-invariant Image Representations 2013](https://arxiv.org/pdf/1301.3224.pdf) - посмотреть ссылки на эту статью

**Comment by vshokorov** [comment]
CODE:
[VAE-PyTorch](https://github.com/shivakanthsujit/VAE-PyTorch)
[pytorch-vae](https://github.com/sksq96/pytorch-vae)
